export const CAMPOS_DETALLE = [
  { col: 'clasificacion', label: 'Clasificación', tipo: 'pildora-simple' },
  { col: 'paisImplementacion', label: 'País de implementación', tipo: 'pildoras-paises' },
  { col: 'descripcion', label: 'Descripción', tipo: 'parrafo' },
  { col: 'tipoInstitucion', label: 'Institución', tipo: 'pildora-simple' },
  { col: 'financiamiento', label: 'Financiamiento', tipo: 'pildoras' },
  { col: 'numIntegrantes', label: 'Número de integrantes', tipo: 'numero' },
  { col: 'audiencia', label: 'Audiencia', tipo: 'pildoras' },
  { col: 'etapa', label: 'Etapa', tipo: 'etapa' },
  { col: 'metodos', label: 'Métodos', tipo: 'pildoras' },
  { col: 'seguimientoDurante', label: 'Seguimiento durante', tipo: 'auto' },
  { col: 'seguimientoDespues', label: 'Seguimiento después', tipo: 'auto' },
  { col: 'temas', label: 'Temas', tipo: 'pildoras' },
  { col: 'existeRepositorio', label: '¿Existe repositorio?', tipo: 'pildora-simple' },
  { col: 'repositorio', label: 'Repositorio', tipo: 'enlace' },
  { col: 'documentacion', label: 'Documentación', tipo: 'pildoras' },
  { col: 'indicadoresExito', label: 'Indicadores de éxito', tipo: 'pildoras' },
  { col: 'metas', label: 'Metas', tipo: 'pildoras' },
  { col: 'factoresDeterminantes', label: 'Factores determinantes', tipo: 'auto' },
  { col: 'proposito', label: 'Propósito', tipo: 'parrafo' },
  { col: 'institucionesGobernanza', label: 'Instituciones de gobernanza', tipo: 'pildoras' },
  { col: 'funcionesEquipo', label: 'Funciones del equipo', tipo: 'pildoras' },
];
